version: '3.8'

services:
  mvc:
    build:
      context: .
      dockerfile: Docker/Dockerfile.dev
    container_name: sucessoeventos-mvc
    volumes:
      - ./:/app
      - /app/obj
    working_dir: /app
    command: >
      bash -c "dotnet restore &&
      dotnet clean && 
      dotnet build && 
      dotnet ef database update &&
      dotnet watch run --urls 'http://0.0.0.0:5149' --no-restore"
    ports:
      - "5149:5149"
    network_mode: host