# Usa a imagem oficial do SDK do .NET para construir o aplicativo
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .